# -*- coding: utf-8 -*-
"""arbDecision2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ViojhFl8UlYJQCxdveahoKv1norg16HZ

**EJERCICO 2: ¿EL PACIENTE TIENE DIABETES?**

Contexto: Un médico quiere predecir si un paciente tiene riesgo de diabetes.

Variables:

IMC (Alto, Normal)
Azucar_Sangre (Alta, Normal)
Actividad_Fisica (Poca, Mucha)
Diabetes ← variable objetivo (Sí, No)
"""

import pandas as pd
import math
from collections import Counter
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import plot_tree
import matplotlib.pyplot as plt

df = pd.DataFrame({

    "IMC":[
        "Alto","Alto","Alto","Normal","Normal",
        "Normal","Alto","Normal","Normal","Alto"
    ],

    "Azucar_Sangre":[
        "Alta","Alta","Normal","Alta","Normal",
        "Normal","Normal","Alta","Normal","Alta"
    ],

    "Actividad_Fisica":[
        "Poca","Mucha","Poca","Poca","Mucha",
        "Poca","Mucha","Mucha","Poca","Poca"
    ],

    "Diabetes":[
        "Sí","Sí","Sí","Sí","No",
        "No","No","No","No","Sí"
    ]
})

print(df)

def entropia(columna):
    valores = Counter(columna)
    total = len(columna)

    ent = 0

    for v in valores.values():
        p = v / total
        ent -= p * math.log2(p)

    return ent

def ganancia_informacion(df, atributo, objetivo):

    ent_total = entropia(df[objetivo])

    ent_atributo = 0

    for valor in df[atributo].unique():

        subset = df[df[atributo] == valor]

        peso = len(subset) / len(df)

        ent_atributo += peso * entropia(subset[objetivo])

    return ent_total - ent_atributo

def gini(columna):

    valores = Counter(columna)

    total = len(columna)

    impureza = 1

    for v in valores.values():

        p = v / total

        impureza -= p**2

    return impureza

def gini_atributo(df, atributo, objetivo):

    total = 0

    for valor in df[atributo].unique():

        subset = df[df[atributo] == valor]

        peso = len(subset)/len(df)

        total += peso * gini(subset[objetivo])

    return total

""" ENTROPÍA TOTAL"""

print(entropia(df["Diabetes"]))

"""Calcular la ganancia de información de cada atributo"""

atributos = ["IMC", "Azucar_Sangre", "Actividad_Fisica"]
for atributo in atributos:
  print(atributo, ":", round(ganancia_informacion(df,atributo,"Diabetes"),4))

"""GINI"""

for atributo in atributos:
    print(atributo, ":", round(gini_atributo(df, atributo, "Diabetes"), 4))

df_ml = df.copy()
encoder = LabelEncoder()

for col in df_ml.columns:
    df_ml[col] = encoder.fit_transform(df_ml[col])

X = df_ml.drop("Diabetes", axis=1)
y = df_ml["Diabetes"]

"""Construir el árbol ID3."""

modelo_id3 = DecisionTreeClassifier(
    criterion="entropy",
    random_state=42
)

modelo_id3.fit(X, y)

plt.figure(figsize=(12,7))

plot_tree(
    modelo_id3,
    feature_names=[
        "IMC",
        "Azucar_Sangre",
        "Actividad_Fisica"
    ],
    class_names=["No","Sí"],
    filled=True,
    rounded=True
)

plt.title("Arbol ID3")
plt.show()

"""CART"""

modelo_cart = DecisionTreeClassifier(
    criterion="gini",
    random_state=42
)

modelo_cart.fit(X, y)

plt.figure(figsize=(12,7))

plot_tree(
    modelo_cart,
    feature_names=[
        "IMC",
        "Azucar_Sangre",
        "Actividad_Fisica"
    ],
    class_names=["No","Sí"],
    filled=True,
    rounded=True
)

plt.title("Arbol CART")
plt.show()

"""Predecir: ¿Un paciente con IMC=Alto, Azucar=Alta, Actividad=Poca?"""

print("Paciente: IMC=Alto, Azucar=Alta, Actividad=Poca")
pred = modelo_id3.predict([[0,0,1]])
print("Resultado:", "Sí" if pred[0] == 1 else "No")